name: CI
on:
  push:
    branches:
      - main
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install NPM dependencies
        run: |
          npm i
          npm run production
