name: Deploy application
on:
  push:
   branches:
    - main
jobs:
  first-job: 
    name: create
    runs-on: ubuntu-latest # required
    steps: # required
      - uses: actions/checkout@v2
        run: |
          npm install
          npm run prod
